extensions:
  health_check:
    endpoint: ":13133"

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [ 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2.5s, 5s, 10s ]
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.route
      - name: exception.type
    aggregation_temporality: "CUMULATIVE"
    metrics_flush_interval: 15s

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp:
    endpoint: http://tempo:4318
    tls:
      insecure: true

  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: default
    username: default
    traces_table_name: otel_traces


service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, spanmetrics, clickhouse]
    metrics:
      receivers: [spanmetrics]
      processors: [batch]
      exporters: [prometheus]
