{
 "title": "Business Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Checkout",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time - Checkout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"get.checkout\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{span_name=\"payment\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"get.checkout\",\n    }[1m])\n  )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"get.checkout\",\n    }[1m])\n  )\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"get.checkout\",\n    }[1m])\n  )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Response Time - Begin Checkout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"begin_checkout\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{span_name=\"begin_checkout\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"begin_checkout\",\n    }[1m])\n  )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"begin_checkout\",\n    }[1m])\n  )\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"begin_checkout\",\n    }[1m])\n  )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Response Time - Payment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"payment\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{span_name=\"payment\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"payment\",\n    }[1m])\n  )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"payment\",\n    }[1m])\n  )\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      span_name=\"payment\",\n    }[1m])\n  )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Checkout Flow",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  StatusCode,\n  count(*) AS total\nFROM default.otel_traces\nWHERE SpanName IN ('get.checkout')\nGROUP BY StatusCode",
       "rawQuery": "/* grafana dashboard='Business Observability', user='0' */\nSELECT\n  StatusCode,\n  count(*) AS total\nFROM default.otel_traces\nWHERE SpanName IN ('get.checkout')\nGROUP BY StatusCode",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Top Exception Errors",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  SpanAttributes['exception.type'] AS \"Exception Type\",\n  count() AS \"Total\"\nFROM default.otel_traces\nWHERE\n  has(SpanAttributes, 'exception.type') AND\n  SpanName = 'get.checkout'\nGROUP BY\n  \"Exception Type\"",
       "rawQuery": "/* grafana dashboard='Business Observability', user='0' */\nSELECT\n  SpanAttributes['exception.type'] AS \"Exception Type\",\n  count() AS \"Total\"\nFROM default.otel_traces\nWHERE\n  has(SpanAttributes, 'exception.type') AND\n  SpanName = 'get.checkout'\nGROUP BY\n  \"Exception Type\"",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}