{
 "title": "Requisições por Endpoint",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total,service_name)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Geral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total de requisições por endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "sum by(span_name) (traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"})",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Distribuição por Status Code",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(http_status_code) (traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "description": "Tempo médio de resposta",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requisições por segundo",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", status_code!=\"STATUS_CODE_OK\"}[1m])",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Erros por Operação",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(http_route, http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^[4][0-9][0-9]\"}[$__rate_interval]))",
       "legendFormat": "{{span_name}}"
      },
      {
       "expr": "sum by(http_route, http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^[5][0-9][0-9]\"}[$__rate_interval]))",
       "legendFormat": "{{span_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p99, p95, p70, p50",
   "type": "timeseries",
   "description": "Average response time and latency.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 2 },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.99, rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.7, rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[5m]))",
     "legendFormat": "p70"
    },
    {
     "expr": "histogram_quantile(0.5, rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[5m]))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Tempo médio de resposta",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribuição por Status Code",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"})",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Erros por Operação",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route, http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\", http_status_code=~\"^[4][0-9][0-9]\"}[$__rate_interval]))",
     "legendFormat": "{{span_name}}"
    },
    {
     "expr": "sum by(http_route, http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\", http_status_code=~\"^[5][0-9][0-9]\"}[$__rate_interval]))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "% Erro Rate",
   "type": "stat",
   "description": "% de requisições com erro por endpoint",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(traces_span_metrics_calls_total{http_status_code=~\"4..|5..\", service_name=\"$service_name\", span_name=\"$endpoint\"}[$__rate_interval]))\n/\nsum(rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_name=\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{span_name}}"
    }
   ]
  }
 ]
}