{
 "title": "System Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total,service_name)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(span_name) (traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"})",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Throughput by Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", status_code!=\"STATUS_CODE_OK\"}[1m])",
     "legendFormat": "{{http_status_code}}-{{span_name}}"
    }
   ]
  },
  {
   "title": "Throughput by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - Average (p50)",
   "type": "stat",
   "description": "Tempo médio de resposta",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(increase(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\",span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Average response time and latency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\"\n    }[1m])\n  )\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\"\n    }[1m])\n  )\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.7,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\"\n    }[1m])\n  )\n)",
     "legendFormat": "p70"
    },
    {
     "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\"\n    }[1m])\n  )\n)",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "OTEL - Status Code Error",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(span_kind, span_name) (rate(traces_span_metrics_calls_total{service_name=\"fastapi-another-one\", status_code=\"STATUS_CODE_ERROR\"}[5m]))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Non 2xx Error Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", http_status_code=~\"^[4][0-9][0-9]\"}[1m]))",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", http_status_code=~\"^[5][0-9][0-9]\"}[1m]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "% Error Rate",
   "type": "stat",
   "description": "% de requisições com erro por endpoint",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(traces_span_metrics_calls_total{http_status_code=~\"4..|5..\", service_name=\"$service_name\"}[$__rate_interval]))\n/\nsum(rate(traces_span_metrics_calls_total{service_name=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Trace List Duration > 100ms",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "filters": [
      { "id": "9daf41ea", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 10,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service_name\" && span:kind=server && duration > 100ms}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Top 10 Exception Errors",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  SpanAttributes['exception.type'] AS \"Exception Type\",\n  SpanName AS \"Route\",\n  count() AS \"Total\"\nFROM default.otel_traces\nWHERE\n  has(SpanAttributes, 'exception.type')\nGROUP BY\n  \"Exception Type\", \"Route\"",
     "rawQuery": "/* grafana dashboard='System Observability', user='0' */\nSELECT\n  SpanAttributes['exception.type'] AS \"Exception Type\",\n  SpanName AS \"Route\",\n  count() AS \"Total\"\nFROM default.otel_traces\nWHERE\n  has(SpanAttributes, 'exception.type')\nGROUP BY\n  \"Exception Type\", \"Route\"",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "description": "Average response time and latency.",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_sum{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m])) * 1) / sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\",\n      span_name=\"$endpoint\"\n    }[5m])\n  )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95,\n  sum by (span_name, le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\",\n      span_name=\"$endpoint\"\n    }[5m])\n  )\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.7,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\",\n      span_name=\"$endpoint\"\n    }[5m])\n  )\n)",
       "legendFormat": "p70"
      },
      {
       "expr": "histogram_quantile(0.5,\n  sum by (span_name, le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"$service_name\",\n      span_kind=\"SPAN_KIND_SERVER\",\n      span_name=\"$endpoint\"\n    }[5m])\n  )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Latency - Average (p50)",
     "type": "stat",
     "description": "Tempo médio de resposta",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5,sum(increase(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\",span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\"}[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput by Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", span_name=\"$endpoint\", status_code!=\"STATUS_CODE_OK\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non 2xx Error Codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_name=\"$endpoint\", http_status_code=~\"^[4][0-9][0-9]\"}[1m]))",
       "legendFormat": "{{http_status_code}}"
      },
      {
       "expr": "sum by(http_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_name=\"$endpoint\", http_status_code=~\"^[5][0-9][0-9]\"}[1m]))",
       "legendFormat": "{{http_status_code}}"
      }
     ]
    },
    {
     "title": "% Error Rate",
     "type": "stat",
     "description": "% de requisições com erro por endpoint",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (sum(rate(traces_span_metrics_calls_total{http_status_code=~\"4..|5..\", service_name=\"$service_name\", span_name=\"$endpoint\"}[$__rate_interval]))\n/\nsum(rate(traces_span_metrics_calls_total{service_name=\"$service_name\", span_name=\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Trace List",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "filters": [
        { "id": "9daf41ea", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [],
         "valueType": "string"
        },
        {
         "id": "span-name",
         "operator": "=",
         "scope": "span",
         "tag": "name",
         "value": [],
         "valueType": "string"
        }
       ],
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"$service_name\" && span:kind=server && name=\"$endpoint\"}",
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "Trace List Duration > 100ms",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "filters": [
        { "id": "9daf41ea", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [],
         "valueType": "string"
        },
        {
         "id": "span-name",
         "operator": "=",
         "scope": "span",
         "tag": "name",
         "value": [],
         "valueType": "string"
        }
       ],
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"$service_name\" && name=\"$endpoint\" && span:kind=server && duration > 100ms}",
       "tableType": "traces"
      }
     ]
    }
   ]
  }
 ]
}